### ISSUE TITLE
Support for ObjectStore.getAll()

### ISSUE THREAD

**Issue by Levi-Lesches** [tekartik/idb_shim.dart#18]
Hi, thanks for making this wonderful package!

Are there any plans to support [`ObjectStore.getAll()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getAll)?

**Comment by alextekartik** [comment]
Thanks. Yeap sounds like a good addition. Unfortunately the dart implementation is not correctly defined in [`dart:indexed_db`](https://api.dart.dev/stable/2.9.1/dart-indexed_db/ObjectStore/getAll.html) yet. I'd rather have the dart team doing the correct implementation (devc and dart2js) rather than doing something wrong. It could also be implemented using a cursor in the meantime but it may not be as efficient.

**Comment by alextekartik** [comment]
Support added for ObjectStore.getAll and ObjectStore.getAllKeys in idb_shim 1.12.0 just published

**Comment by Levi-Lesches** [comment]
Thanks! Not quite sure what changed but this is helpful! In the meantime I was using this code: 

```dart
Future<List<T>> getAll(String storeName) async => [
  await for (
    final CursorWithValue cursor in database,transaction(storeName, idbModeReadOnly)
      .objectStore(storeName)
      .openCursor(autoAdvance: true)
  ) cursor.value
];
```
